import { FlatCompat } from "@eslint/eslintrc";
import localRules from "./eslint-rules/no-physical-direction.mjs";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    plugins: { local: localRules },
    rules: {
      "local/no-physical-direction": "error",
    },
  },
  {
    // next-env.d.ts is gitignored and regenerated by `next dev`/`next build`
    // (not present in a fresh checkout until the first run) — it's a
    // Next.js-owned file ("this file should not be edited") that happened
    // to surface a lint error here once actually running the app locally.
    ignores: [
      ".next/**",
      "node_modules/**",
      "supabase/**",
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
