// DEPLOYMENT.md §5: "the app checks at boot that the DB's
// schema_migrations head matches the version compiled into the build."
// This script computes that compiled-in version from the migration files
// present at build time and writes it to src/generated/schema-version.ts.
// Run automatically via the `prebuild`/`predev` npm/pnpm lifecycle hooks
// (see package.json).
//
// Supabase CLI records each applied migration's version as the numeric/
// timestamp prefix before the first underscore in its filename (e.g.
// "0001_init.sql" -> "0001"). We take the lexicographically-highest prefix
// across supabase/migrations/*.sql as the "head" version.
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(__dirname, "..", "supabase", "migrations");
const outDir = join(__dirname, "..", "src", "generated");
const outFile = join(outDir, "schema-version.ts");

function main() {
  const files = readdirSync(migrationsDir).filter((f) => f.endsWith(".sql"));
  if (files.length === 0) {
    throw new Error(`No migration files found in ${migrationsDir}`);
  }
  const versions = files
    .map((f) => f.split("_")[0])
    .filter((v): v is string => Boolean(v))
    .sort();
  const head = versions[versions.length - 1];

  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    outFile,
    `// GENERATED by scripts/generate-schema-version.ts — do not edit by hand.\n` +
      `// Recomputed on every build/dev start from supabase/migrations/*.sql.\n` +
      `export const EXPECTED_SCHEMA_VERSION = ${JSON.stringify(head)};\n`,
  );
  console.log(`[generate-schema-version] EXPECTED_SCHEMA_VERSION = ${head}`);
}

main();
